#!/bin/bash

yum -y update;
yum -y install wget;
yum -y install nano;
yum -y install rsync;

wget https://github.com/prometheus/node_exporter/releases/download/v1.6.0/node_exporter-1.6.0.linux-amd64.tar.gz;
tar xf node_exporter-1.6.0.linux-amd64.tar.gz
useradd --no-create-home --user-group --shell=/usr/sbin/nologin node_exporter
rsync -abvuP  --chown=node_exporter:node_exporter /home/kostya/node_exporter-1.6.0.linux-amd64/node_exporter /usr/local/bin/
wget -m --user=back --password=backup ftp://192.168.88.60/node_exporter.service
rsync -advuP /home/kostya/192.168.88.60/node_exporter.service /etc/systemd/system
systemctl daemon-reload
systemctl start node_exporter
systemctl enable node_exporter

rpm -Uvh https://repo.mysql.com/mysql80-community-release-el7-7.noarch.rpm
sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/mysql-community.repo
yum --enablerepo=mysql80-community install mysql-community-server

sed -c -i "s/\SELINUX=.*/SELINUX=disabled/" /etc/sysconfig/selinux

systemctl start mysqld
systemctl enable mysqld

hostnamectl set-hostname mysql-salve

grep "A temporary password" /var/log/mysqld.log

systemctl stop firewalld;
systemctl disable firewalld;

mysql_secure_installation;

wget -m --user=back --password=backup ftp://192.168.88.60/db_drupal ftp://192.168.88.60/mysql_master/my.cnf

gunzip 192.168.88.60/db_drupal/*

mv /home/kostya/192.168.88.60/mysql_master/my.cnf /etc/

mysql -e "CREATE DATABASE db_drupal";
mysql -e "CREATE USER 'drupal'@'%' IDENTIFIED BY '1Drupal!'";
mysql -e "GRANT ALL PRIVILEGES ON db_drupal.* TO 'drupal'@'%'";
mysql -e "CREATE USER 'repl@'%' IDENTIFIED WITH 'caching_sha2_password' BY 'oTUSlave#2020'";
mysql -e "GRANT REPLICATION SLAVE ON *.* TO 'repl'@'%'";
mysql -e "FLUSH PRIVILEGES";


for filename in `find /home/kostya/192.168.88.60/db_drupal/ -d -name "*"`
    do
        mysql db_drupal <  $filename
    done
